#!/bin/bash


# Building the .pro file using qmake

rm -f qrc_icons.cpp geCache.pro Makefile

qmake -project -o geCache
cat >geCache.tmp <<EOF
RC_FILE = geCache.rc
RESOURCES = icons.qrc
QT += widgets
CONFIG += console
EOF


cat geCache.pro >>geCache.tmp
mv geCache.tmp geCache.pro


# Building the Makefile file using qmake

qmake -o Makefile



make


export DESTINATION=${1:-"."}
mv geCache $DESTINATION


# Get rid of the Makefile so there is no confusion.  It will be generated again the next time we build.

rm Makefile
